### ISSUE TITLE
Cannot disable form inputs

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#759] opened 2020-03-17 04:57 UTC
## This is:

- Bug

## Detailed Description
Passing a `disabled={true}` prop on components like `Input` and `Select` does not have any effect. For example:

https://storybook.webiny.com/?path=/story/components-input--usage
https://storybook.webiny.com/?path=/story/components-select--usage

It works in the RMWC library - https://rmwc.io/text-fields.

Not sure where the bug is but if I hardcoded the `disabled={true}` in `packages/ui/src/Input/Input.tsx:112`, all inputs would become disabled as expected:

![image](https://user-images.githubusercontent.com/5121148/76823561-e2af5f00-6814-11ea-8195-e8f3ed202238.png)

So, it seems that the flag is not correctly passed to the actual RMWC `TextArea` component.

**Comment by ahmad-reza619** [comment] 2020-03-21 05:42
hey @doitadrian i've seen the Input component, is it possible for missing prop types cause this? i think the implementation is already good

**Comment by Pavel910** [comment] 2020-03-21 11:31
@ahmad-reza619 what do you mean by `missing prop types`?

**Comment by ahmad-reza619** [comment] 2020-03-21 11:43
@Pavel910 the Input component has no disabled prop types, but it use disabled prop, so I think it automatically remove props that doesn't specified in prop type. It's just my guess actually, I never used typescript before

**Comment by Pavel910** [comment] 2020-03-21 11:48
Actually that’s not correct, as you can see we compose types by importing the original Rmwc type and add our own props on top of that.

Also, TS doesn’t remove anything, no tools do. You can’t remove a prop from component; whatever is passed to component will be in the props object at runtime.

This is an interesting bug, I’ll take a look at it as well.

**Comment by doitadrian** [comment] 2020-03-27 09:35
I found the issue here. Actually, it's related to the `Bind` component and how it spreads props to the child component:

`packages/form/src/Bind.ts:78`:
![image](https://user-images.githubusercontent.com/5121148/77741729-ac908d00-7015-11ea-85cb-5fe06c9a7fe2.png)


Changing this to the following fixed the issue:

![image](https://user-images.githubusercontent.com/5121148/77742307-946d3d80-7016-11ea-9479-e8309faf9b8b.png)

**Comment by ahmad-reza619** [comment] 2020-03-28 11:44
Is it already fixed?

**Comment by Pavel910** [comment] 2020-03-28 11:47
@ahmad-reza619 nope, feel free to submit a PR if you'd like to take on this :)

**Comment by ahmad-reza619** [comment] 2020-03-28 15:14
Alright will do, but wow, i never thought another component is the cause of all this 🤔 how is it even possible? is Bind forward it props to the children?

**Closed** 2020-04-02 09:30 UTC
Labels: bug, good-first-issue
