### ISSUE TITLE
Improve admin app navigation

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1259] opened 2020-09-23 09:25 UTC
## This is:
- Feature request

## Detailed Description
Our current navigation in the admin app needs several improvements:
- [ ] Convert bottom items (links to source, community, etc) to plugins, so users can remove/override those in their projects
- [ ] Fix API Information icon to match the style of other navigation icons

This is the part of navigation I'm talking about:
![image](https://user-images.githubusercontent.com/3920893/93993291-dc370c80-fd8e-11ea-93a8-b21d25bbe9bf.png)

**Comment by SvenAlHamad** [comment] 2020-09-23 09:28
On this one, let's also replace `community` with `slack`.

**Comment by Lavish-Garg** [comment] 2020-10-01 19:19
i have to change api icon from code or i can post the image here?

**Comment by Pavel910** [comment] 2020-10-01 19:23
@Lavish-Garg the `API Information` icon is an SVG, but its size doesn't match the other icons below it. THere is something wrong with the width, or something. You'll need to change it through code.

**Comment by lokeshvenkatesan** [comment] 2020-10-03 06:28
I am Taking up this issue

**Comment by ShyamPraveenSingh** [comment] 2020-10-05 03:27
Hi @Pavel910, I would like to work on this issue. 
Can you please assign it to me?

**Comment by aloks98** [comment] 2020-10-05 16:18
@Pavel910 why arent we using `<Link>` from `@webiny/react-router` in Footer? I can take up this issue can make changes.

**Comment by Pavel910** [comment] 2020-10-06 08:04
@aloks98 because `<Link>` is mostly for public apps where we have internal links pointing to, say, Page Builder pages. That component then preloads data for faster page transitions. In admin app such routes do not exist, so we don't use it there.

**Comment by AlbionaHoti** [comment] 2020-10-06 08:27
Hi, can you please confirm if you are working on the issue? If not, the next person will get the assignment. We need confirmation from everyone in order:

- [ ]  @Lavish-Garg
- [ ]  @lokeshvenkatesan 
- [ ]  @ShyamPraveenSingh 
- [ ]  @aloks98

**Comment by BhuwanChandra** [comment] 2020-10-06 19:36
Hey @AlbionaHoti If no one is working on this issue, I would like to take this. please assign this to me.

**Comment by AlbionaHoti** [comment] 2020-10-06 20:27
Hey, @BhuwanChandra you are on the list, next @aloks98 - We will wait for a confirmation and decide on the assignment. Meanwhile, did you follow up on the [Contributing.md](https://github.com/webiny/webiny-js/blob/master/docs/CONTRIBUTING.md?utm_source=GitHub&utm_medium=webiny-github-contributing&utm_campaign=webiny-discussions-oct-5&utm_content=webiny-contributing-guide&utm_term=W00168) guides to set up Webiny locally?

**Comment by aloks98** [comment] 2020-10-06 22:35
@Pavel910 i am open to work on this issue, and yes, I have set up webiny locally. I have been working on another issue too and about to complete it. 😄

**Comment by AlbionaHoti** [comment] 2020-10-07 15:01
@aloks98 Please reach out again when the other issue is complete and merged. Until then, this issue is open for other contributors, if any :)

**Comment by BhuwanChandra** [comment] 2020-10-07 15:17
@AlbionaHoti if this is open, I would like to work on it!

**Comment by AlbionaHoti** [comment] 2020-10-07 15:33
@BhuwanChandra you can continue on the issue. Please post an update of where you think the problem is after diagnosing it and the solutions you tried (communication here is key) - Join our slack community to communicate faster with the community and the core team. Enjoy :)

**Comment by lokeshvenkatesan** [comment] 2020-10-08 05:56
I am working on this issue. Please send me slack join link. Thank you.

**Comment by Ashu96** [comment] 2020-10-08 06:49
@lokeshvenkatesan Please join [Slack](https://www.webiny.com/slack/) :slightly_smiling_face:

**Comment by AlbionaHoti** [comment] 2020-10-08 11:44
@lokeshvenkatesan @BhuwanChandra is working on this issue, until we have an update from him on the progress we can't assign the issue to someone else. Thank you.

**Comment by BhuwanChandra** [comment] 2020-10-08 13:59
@AlbionaHoti I did the local setup of webiny, also went through the code files and looked at where to make changes to solve the issue. I am working on it and will make a PR soon.

**Comment by BhuwanChandra** [comment] 2020-10-14 04:12
@AlbionaHoti I have created a PR #1298 for this issue, can you review it and suggest some improvements(if any)?

**Comment by AlbionaHoti** [comment] 2020-10-14 09:31
@BhuwanChandra thank you very much for the PR, our team member @Ashu96 will get back to you later today with feedback!

**Closed** 2020-10-19 03:53 UTC
Labels: feature, good-first-issue, hacktoberfest, improvement

**Comment by lokeshvenkatesan** [comment] 2020-10-19 04:25
Sorry to mention.
We have been suffering from Pandemic and we are struggling to cope up.
I am interested in getting webiny swags and due to pandemic I am not able
to complete the work.

Let me know what's need to be done for minimum requirements to obtain
webminy swags .


Sorry for delay. Regret for the inconvenience.

Thank you
Lokesh
