### ISSUE TITLE
Save block notification doesn't go away

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#391] opened 2018-12-27 17:10 UTC
When you save a block, you get a notification that the block was successfully saved, but the notification doesn't go away.

**Comment by doitadrian** [comment] 2018-12-28 18:46
@SvenAlHamad 

Couldn't reproduce this one, can you?

Have in mind that sometimes this might happen because of webpack.

If you cannot reproduce, we can close this one I guess.

**Closed** 2019-10-27 11:41 UTC
