### ISSUE TITLE
Editor - trim long titles

### ISSUE THREAD

**Issue by adrian1358** [Webiny/webiny-js#242] opened 2018-10-21 17:56 UTC
![image](https://user-images.githubusercontent.com/5121148/47270368-3740a300-d56b-11e8-9e81-682e054f823d.png)

**Comment by Pavel910** [comment] 2018-10-22 07:29
Duplicate of #236

**Closed by Pavel910** 2018-10-22 07:29 UTC
Labels: tag: bug fix, webiny-api-cms

**Comment by adrian1358** [comment] 2018-10-22 07:34
Great @Pavel910, thanks for closing!
