### ISSUE TITLE
Disabling the GRAPHQL PLAYGROUND is NOT disabled when setting GRAPHQL_PLAYGROUND: false in your .env.json file

### ISSUE THREAD

**Issue by tbender-unicon** [webiny/webiny-js#1285] opened 2020-10-05 15:15 UTC
## This is:

- Bug

## Specifications

  - version: 4.9.0 ?
  - OS: OS X 10.13.6
  - Browser: Chrome, Friefox

## Expected Behavior
  - when I visit the graphql URL in a web browser, it provides the same response as if the page does not exist. e.g. 404?

## Actual Behavior
  - GraphQL Playground appears and is 100% usable

## Steps to Reproduce the Problem

1. Set the .env.json in your api directory  `./api/.env.json`
2. re-build and re-deploy the application
3. visit provided graphql playground link as provided from webiny build & deploy output

## Possible Solution

Application returns a 404 -- Page not found

**Comment by tbender-unicon** [comment] 2020-10-05 15:16
{
        "default": {
                "GRAPHQL_INTROSPECTION": false,
                "GRAPHQL_PLAYGROUND": false,
                "S3_BUCKET": "webiny-js-files-9e90cfae",
                "JWT_SECRET": "RMbUslezA4bWQhXnwYUuX6eSpI+9cTnC6VV6B2sQTJzZ6W6x5D6T1isjHKKC"
        }
}

**Comment by doitadrian** [comment] 2020-10-05 17:15
Duplicate of https://github.com/webiny/webiny-js/issues/1283 (which was fixed by @Ashu96). Closing.

**Closed by doitadrian** 2020-10-05 17:15 UTC
