### ISSUE TITLE
Cannot create an entry when model has a Text field with multiple values enabled and the field is left blank.

### ISSUE THREAD

**Issue by uncle-mo** [webiny/webiny-js#2612] opened 2022-09-08 02:28 UTC
### Version

5.30

### Operating System

Windows

### Browser

Chrome

### What are the steps to reproduce this bug?

- Create a model with a "Text" field with "use as a list of text" option set.
- Try to Create an entry for the model without adding anything to the new Text field list.

### What is the expected behavior?

Entry should be be created with null value.

### What do you see instead?

Hangs on spinner.

Error: GraphQL error: Variable "$data" got invalid value null at "data.tags[0]"; Expected non-nullable type "String!" not to be null.

**Comment by Pavel910** [comment] 2022-09-08 07:52
Closing as a duplicate of https://github.com/webiny/webiny-js/issues/2468. Please leave a +1 there to improve visibility. Thanks a lot!

**Closed as completed by Pavel910** 2022-09-08 07:52 UTC
Labels: duplicate, bug
