### ISSUE TITLE
App Admin: Hide settings section if it is empty

### ISSUE THREAD

**Issue by latotty** [webiny/webiny-js#1223] opened 2020-09-10 13:48 UTC
## This is:

- Bug
- Feature request

## Specifications

  - version: 4.11.0

## Expected Behavior

If there is no `admin-menu-settings` plugins, it shouldn't be rendered.
Also if all the settings items rendering `null` (because of permission) it shouldn't render the settings.

## Actual Behavior

It is rendered empty.

## Steps to Reproduce the Problem

Remove all the `admin-menu-settings` and check the menu.

## Detailed Description

I use the app-admin as a dashboard for my client. And all my settings has permission guard, and it looks odd, when a user with no permission for settings see an empty settings section.

I could bypass it by overwriting the `webiny-init-settings` plugin, but it would be great if it would be automatic.

## Possible Solution

https://github.com/webiny/webiny-js/blob/ee1dadbcece0929a4fe259f9051554249012c043/packages/app-admin/src/plugins/init.tsx#L22-L32
```typescript
            render({ Menu, Section, Item }) {
                const items = settingsPlugins
                    .map(plugin => ({ name: plugin.name, element: plugin.render({ Section, Item }) }))
                    .filter(({ element }) => !!element);

                return (
                    <Menu name="settings" label={t`Settings`} icon={<SettingsIcon />}>
                        {items.map(({ name, element }) => (
                            <React.Fragment key={name}>
                                {element}
                            </React.Fragment>
                        ))}
                    </Menu>
                );
            }
```

**Comment by Pavel910** [comment] 2020-09-10 13:51
@latotty duplicate of #1073, so I'll close this issue in favor of the other one.

**Closed by Pavel910** 2020-09-10 13:51 UTC

**Comment by latotty** [comment] 2020-09-10 13:55
> @latotty duplicate of #1073, so I'll close this issue in favor of the other one.

Sorry didn't see it.
I've added a PR also, you could delete it if it is unnecessary.
