### ISSUE TITLE
Heading element in a Block shows <br> attached to the default value

### ISSUE THREAD

**Issue by ma-schmidt-de** [webiny/webiny-js#3225] opened 2023-04-21 07:42 UTC
### Version

5.34.7

### Browser

Firefox 112.0.1

### What are the steps to reproduce this bug?

* Create a new Block
* Add the `Heading` page element
* Modify the default value
* Link Element in order to create a variable for this page element
* `Save Changes`
* Create a new page, with arbitrary category and add the block you just created
* Attempt to change the default value

### What is the expected behavior?

Only the default value of the `Heading` element is pre-set in the as the variable.

### What do you see instead?

The variable contains the default value but with a `<br>` attached.

![Screenshot 2023-04-21 at 09 36 04](https://user-images.githubusercontent.com/19306046/233574027-07e84dab-ac3a-47ef-8669-ca9bddf0707a.png)

### Additional information

A quick chat with @adrians5j confirmed, it's worth a issue here and some further investigation.
Cheers.

**Comment by SvenAlHamad** [comment] 2023-04-24 15:34
Similarly to #3226 this one will be fixed with the v5.35 release and introduction of Lexical editor. Closing for now, but if after the release the issue is present, feel free to reopen the issue.

**Closed as completed by SvenAlHamad** 2023-04-24 15:34 UTC
Labels: bug
