### ISSUE TITLE
No Model Entry autoload/scrollbar on big screens

### ISSUE THREAD

**Issue by ProjectDocHelp** [webiny/webiny-js#2819] opened 2022-12-02 09:44 UTC
### Version

5.33.3

### Operating System

Win

### Browser

Chrome

### What are the steps to reproduce this bug?

Have a big screen (1600 px in height). Open Webiny in a maximized browser and go to a content with multiple entries.

### What is the expected behavior?

To see as many entries as fit the screen, a scrollbar and auto reload after scrolling.

### What do you see instead?

Just the first 10 entries without a scrollbar. If I make the borwser window smaller, the scollbar will appear and scolling will load the next batch of entries. Once the scrollbar is visible, also maximizing and scrolling will behave as expected.

**Comment by brunozoric** [comment] 2023-01-24 14:43
Duplicate of #2781

**Closed as completed by brunozoric** 2023-01-24 14:43 UTC
Labels: bug
