### ISSUE TITLE
Unable to deploy custom app since 5.18

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#2067] opened 2021-11-30 02:05 UTC
### Version

5.18.2

### Operating System

MacOS

### Browser

Firefox

### What steps will reproduce the bug?

The pulumi script for my custom app is no longer able to find the pulumi binary dir: .webiny/pulumi-cli/linux/pulumi when run in a container in the CI environment, leading to a failure during deploy.  If I manually add that dir to my path before deploying, it works.  It also works locally, probably because I have a separate pulumi installation later in my path.  

The files exist and are executable, so it seems like there's something happening in the webiny deploy command that's failing to set the path correctly.

### What is the expected behavior?

The app should build and deploy.

### What do you see instead?

```
yarn webiny --env ${ENVIRONMENT} deploy connect-web
webiny info: Building connect-web package...
[info] [webpackbar] Compiling Code
[success] [webpackbar] Code: Compiled successfully in 37.41s
Compiled successfully.
File sizes after gzip:
  599.7 KB  build/static/js/2.f9294dc1.chunk.js
  52.7 KB   build/static/js/main.cc03f785.chunk.js
  52.63 KB  build/static/css/main.df54df45.chunk.css
  733 B     build/static/js/runtime-main.ca88d66a.js
webiny success: Successfully built connect-web in 48.024s.
webiny info: Running "hook-before-deploy" hook...
webiny info: Using profile undefined in us-east-1 region.
webiny success: Hook "hook-before-deploy" completed.
webiny info: Deploying...
Updating (scott):
 
webiny error: Command failed with exit code 255: /builds/1iy2Y75r/0/veevashare/connect/.webiny/pulumi-cli/linux/pulumi/pulumi up --yes --skip-preview --secrets-provider passphrase --non-interactive
error: could not load plugin for pulumi-nodejs provider 'urn:pulumi:scott::connectWeb::pulumi:providers:pulumi-nodejs::default': no resource plugin 'pulumi-nodejs' found in the workspace or on your $PATH
```

### Additional information

This is a 5.18 regression of some sort.  It works in 5.17.  It is also specific to the custom app.  Api and admin both deploy normally.

**Comment by adrians5j** [comment] 2021-11-30 06:30
For 5.18.0, we had a change [here](https://github.com/webiny/webiny-js/blob/next/packages/pulumi-sdk/src/index.ts#L94-L100).

Now, I don't know if this could be the cause, but maybe we could check it out. So, let's maybe try forcing the 5.17.0 version of the `@webiny/pulumi-sdk` package by assigning `"@webiny/pulumi-sdk": "5.17.0"` in the root package.json file, in the `resolutions` property: 

![image](https://user-images.githubusercontent.com/5121148/143996958-a8e86e91-76c9-4d39-b8fa-359b7083fb86.png)

Sorry for the inconvenience, hopefully we'll get to the bottom of this.

P.S. Your custom app... does it have any custom Pulumi code? Or it was an app created with the scaffold and you're just using the code that was already scaffolded in there?

**Comment by snstanton** [comment] 2021-12-01 00:39
Oh, I think that delta is the issue.  It's using a Windows style semicolon path separator, but this is Linux, so it should be a colon.  Or more accurately, it should be:
```
 PATH: `${process.env.PATH}${path.delimiter}${this.pulumiFolder}`
```

**Comment by snstanton** [comment] 2021-12-01 01:27
And I can confirm that rolling it back to 5.17 does work.  Although to get things working properly, I have to use this set of resolutions:  
<img width="309" alt="image" src="https://user-images.githubusercontent.com/209370/144154965-f3acc24c-8ec4-4945-bed3-c948c9999313.png">
If I don't add the two pulumi lines, I get errors like:
```
    error: Running program '/Users/scotts/workspace/connect/api/pulumi' failed with an unhandled exception:
    Error: The root stack resource was referenced before it was initialized.
```

**Comment by adrians5j** [comment] 2021-12-13 09:53
Closed by https://github.com/webiny/webiny-js/pull/2084.

**Closed as completed by adrians5j** 2021-12-13 09:53 UTC
