### ISSUE TITLE
Updating permissions of an api key causes the key to vanish

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#2230] opened 2022-02-09 18:05 UTC
### Version

5.22.1

### Operating System

MacOS

### Browser

Firefox

### What steps will reproduce the bug?

1. Create a new api key with full permission to Content.
2. Save the key and see that it shows up in the key list
3. Add permission to form builder
4. Save the key and see that it no longer shows up in the key list, even with a refresh

### What is the expected behavior?

The updated key should show up in the list and have the new permissions.

### What do you see instead?

The updated key is no longer present in the list and the token is no longer accepted in api calls.

### Additional information

This is a ddb+es installation.

**Comment by larissa-n** [comment] 2022-02-10 15:43
Can confirm this is still a problem.

I see the related #2206 was closed. @Pavel910, does #2221 fix this issue and when do you think we'll get a release that has this fix?

So far it's impossible to generate API keys with any sort of custom access (and I believe full access doesn't provide any writing privileges, but I can't find much about it in the docs.) Is there any workaround?

**Comment by Pavel910** [comment] 2022-02-10 16:08
@larissa-n just assigned a milestone to the PR. It will be out in `5.23` landing next week.

**Comment by Pavel910** [comment] 2022-02-10 16:08
Closing as duplicate of #2206

**Closed as completed by Pavel910** 2022-02-10 16:08 UTC
